---
name: MinIO Rust Library

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Check style
      run: |
        cargo build --verbose
        cargo fmt --all -- --check

    - run: rustup component add clippy

    # Do not use gh-actions/clippy cause of the
    # https://github.com/dna2fork/tensorboard/commit/5d560de192ce2b73a05535fbc8ee8f2f0c4a2221
    - run: cargo clippy --all-targets --all-features

    - name: Run tests
      run: |
        ./tests/start-server.sh
        export SERVER_ENDPOINT=localhost:9000
        export ACCESS_KEY=minioadmin
        export SECRET_KEY=minioadmin
        export ENABLE_HTTPS=1
        export SSL_CERT_FILE=./tests/public.crt
        cargo test --verbose -- --nocapture
